# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test
    ##### Docker image creation ##########
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
    
    - name: Build and push to Docker
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: prathikmanchikalapudi/client:latest
    
    - name: Image Digest
      run: echo ${{steps.docker_build.outputs.digest}}
    
    #### deploy in netlify#####
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        NETLIFY_SITE_ID: ${{secrets.NETLIFY_SIDE_ID}}
      with:
        args: deploy --dir=build --prod
        #secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

